# Generated by Django 5.0.2 on 2024-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super',
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(default='student', max_length=20, null=True),
        ),
    ]
